### ISSUE TITLE
would you give me permission to continue this project

### ISSUE THREAD

**Issue by hanicraft** [luizeldorado/webgm#3]
hi your project seems pretty awesome, its sad you abandoned it 
but anyway since you are abandoned it, would you give me permission to continue development of it by forking it

**Comment by luizeldorado** [comment]
Hi, hanicraft, thank you for your interest.

As it's a GPL licensed project, anyone can fork it if they want to. But I rather you send in pull requests for this repository; I'll gladly review and accept it and merge it if it improves the project.

However, as I said in #2, there's probably other projects that might be a better use of your time.
